---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: es-pv
spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /home/nfsdata
      server: 10.0.60.51
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-pvc
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi